# Generated by Django 2.1.7 on 2019-04-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0004_auto_20190412_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='img',
            field=models.ImageField(default='https://www.google.com/url?sa=i&source=images&cd=&cad=rja&uact=8&ved=2ahUKEwi-0tX8vcrhAhUSAWMBHSsjAN8QjRx6BAgBEAU&url=http%3A%2F%2Fdailyphotoalbums.blogspot.com%2F2011%2F10%2Fbooks-notes.html&psig=AOvVaw2NWaCkvVTjgj16WRmhepG1&ust=1555156069296762', upload_to='notes-img'),
        ),
    ]
