# Generated by Django 2.1.7 on 2019-04-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0005_auto_20190412_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='img',
            field=models.ImageField(default='http://1.bp.blogspot.com/-dM8sD2C1JUI/TpN55SW_9YI/AAAAAAAAAGY/tWPDAMDmUA4/s1600/180557_151900304867170_117131591677375_294067_83040_n.jpg', upload_to='notes-img'),
        ),
    ]
