# Generated by Django 2.1.7 on 2019-04-12 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0006_auto_20190412_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='img',
            field=models.ImageField(upload_to='notes-img'),
        ),
    ]
